#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color'
alias mocp='mocp -T /usr/share/moc/themes/hacker_theme'
alias cal='cal -m'
alias date='date "+%Y-%m-%d %H:%M:%S"'

PS1='[\u@\h \W]\$ '

complete -cf sudo
complete -cf man

source /usr/share/git/completion/git-completion.bash

export PATH=$PATH:$HOME/projects/tools/:$HOME/projects/coinmon.py/:$HOME/projects/termrea/termrea/:$HOME/.symfony/bin/:$HOME/.config/composer/vendor/bin/:$HOME/.gem/ruby/3.0.0/bin/
export VISUAL="vim"
export HISTCONTROL=ignoreboth
